Update INSTALL.md #165
LesFruitsDefendus/saskatoon-ng pull request #203
Opened 2022-04-07 21:29 UTC by richarddushime

On cloning, installing the requirements and running the Saskatoon-ng repo some errors occured
#165
to solve this issue  i updated even  env.template file by adding the export keyword  the  variables

2022-04-08 15:52 UTC, tristanlatr approved these changes
Hi @richarddushime,

Glad to see that your issue got resolved. 

I feel like this change should not be necessary for django-dotenv to read your config file.
But since [it supports adding the export keyword](https://github.com/jpadilla/django-dotenv/blob/c68fd4bf3ae330c7160a620210f760f0a52359fd/tests.py#L68), I don't see any reason why not adding it.

2022-04-10 23:45 UTC, 2ynn commented on INSTALL.md
>  Example mysql configuration in *.env* file:
@richarddushime here we specify the content goes in the `.env` file (to be parsed by `django-dotenv`)

2022-04-10 23:46 UTC, 2ynn commented
@richarddushime same i'm gonna close this one, let me know if you still have issues importing environment variables by adapting the current `.env` template file.

2022-04-10 23:48 UTC, 2ynn commented
@richarddushime  @tristanlatr sorry just saw the comment about `django-dotenv` supporting the `export` keyword. My bad!
I don't think it's necessary though. Let me know how you feel about it.

2022-04-11 07:39 UTC, richarddushime commented
> @richarddushime @tristanlatr sorry just saw the comment about `django-dotenv` supporting the `export` keyword. My bad! I don't think it's necessary though. Let me know how you feel about it.

on my side i faced several errors while setting up the project and i tried to fixed the issue in several ways  still  could read  the .env  file variables  at the end i got a  quick solution for the problem  by using the ``` export ```keyword in the file though there is([supports adding the export keyword](https://github.com/jpadilla/django-dotenv/blob/c68fd4bf3ae330c7160a620210f760f0a52359fd/tests.py#L68),)  Actually i also guided someone  who was facing the same issue   and it worked well with export keyword in .env file

2022-04-12 18:01 UTC, tristanlatr requested changes
Yeah, 

I'm not sure we should introduce these changes, I kinda agree with @2ynn  on that. 
I think the issue resides in the location of the `.env` file being for clear enough, but I'm not certain.

Sorry for the trouble setting up saskatoon @richarddushime.

The little docs additions in the `INSTALL.md` looks good nonetheless.

2022-04-12 18:45 UTC, 2ynn commented
Yea I agree the sentence "Copy the `saskatoon/env.template` file into `saskatoon/.env` and adapt it to your needs." could be improved.
What I meant by this is that the `.env` file must be copied at the same location as the template file, i.e.:
```
cp saskatoon/env.template saskatoon/.env
```
And "to your needs" could for sure be improved, (e.g. detailing that the secret key must be added to the file after being generated etc...)

2024-10-22 03:18 UTC, closed without merging