[#211] Add custom error pages
LesFruitsDefendus/saskatoon-ng pull request #219
Opened 2022-04-10 18:59 UTC by victorphoenix3

Error pages created:

- [x] 400
- [x] 403
- [x] 403 CSRF Token invalid
- [x] 404
- [x] 500

Fixes: #211

Signed-off-by: Jayati Shrivastava <gaurijove@gmail.com>

2022-04-10 19:02 UTC, victorphoenix3 commented
<img width="720" alt="403" src="https://user-images.githubusercontent.com/48182195/162635430-486f79e8-667e-4249-94a2-12a802101768.png">

2022-04-11 02:21 UTC, tristanlatr commented
Hi @victorphoenix3, thanks a lot for this, it shall be useful I think.

Just a question: Does it replaces the default error pages even when `DEBUG=True` ?
I think it would be good to keep the verbose error pages for development. 

Tell me what you think,

Thanks

2022-04-11 06:01 UTC, victorphoenix3 commented
@tristanlatr No, with `DEBUG=True`, we get the default django error pages

2022-04-14 17:19 UTC, tristanlatr requested changes
Hi @victorphoenix3, 

I was going to merge this PR when I realized that we could use translations there too, that would be good. So there are accompanying suggestions to add the translate fucntion.

Thanks a lot,

2022-04-14 17:19 UTC, tristanlatr commented on saskatoon/sitebase/templates/app/errors/400.html
> +                <h1> 400 Bad Request</h1>
```suggestion
                <h1> {% translate "400 Bad Request" %} </h1>
```

2022-04-17 21:59 UTC, tristanlatr commented
Hi @victorphoenix3, could you update this branch with develop ?

Thanks,

2022-04-17 22:29 UTC, victorphoenix3 commented
@tristanlatr done

2022-04-25 10:34 UTC, 2ynn approved these changes
great thanks!

2022-04-26 23:55 UTC, tristanlatr approved these changes

2022-04-26 23:55 UTC, merged