Add swagger-ui support
LesFruitsDefendus/saskatoon-ng pull request #310
Opened 2022-06-10 16:54 UTC by mina-andajos

Fixes #issue-number
----------
## Type of change:
- [x] New feature (change which adds functionality).
----------
## What's Changed:
- Added swagger-ui support, exposed a url & added dependencies to `setup.py` 

--------
## Screenshots:
1. 
![image](https://user-images.githubusercontent.com/52796958/173114224-c8eb2fb1-f546-4423-84a4-9c9a21c15e2a.png)

--------
## Affected URLs:
e.g. `127.0.0.1:8000/swagger/`

-------
## Checklist:
- [x] My code follows the [style guidelines](https://github.com/LesFruitsDefendus/saskatoon-ng/blob/develop/CONTRIBUTING.md) of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] New and existing unit tests pass locally with my changes.

2022-06-10 17:06 UTC, mina-andajos commented
@2ynn hi, I tried implementing the DRF browsable API but couldn't find a helpful documentation or guide. So I thought of implementing drf-yasg instead, swagger has a very similar functionality I believe.

2022-06-11 14:40 UTC, 2ynn commented
@mina-andajos you have to add 
` 'rest_framework.renderers.BrowsableAPIRenderer', ` to  `'DEFAULT_RENDERER_CLASSES'` in settings.py

Then if you don't provide any template_name to your view, it should fall back to the Browsable API:
```
    def retrieve(self, request, *args, **kwargs):
        ### self.template_name = 'app/detail_views/harvest/view.html'
        return super(HarvestViewset, self).retrieve(request, *args, **kwargs)
```

2022-06-11 14:43 UTC, 2ynn commented
@mina-andajos swagger is nice for documentation and testing but I find using filters and links in the default Rest Browser API more convenient for developing.

2022-06-17 05:36 UTC, 2ynn requested changes

2022-06-17 05:36 UTC, 2ynn commented on saskatoon/saskatoon/urls.py
> +    permission_classes=[permissions.AllowAny],
@mina-andajos let's at least enforce `IsAuthenticated` permission.
Alternatively we could also write a custom `IsAdmin` permission, similar to `IsCoreOrAdmin` in `harvest.permissons`

2022-06-19 10:59 UTC, mina-andajos commented
I'm closing this, changing branch and implementing the drf browsable api instead of swagger

2022-06-19 10:59 UTC, closed without merging